server:
  port: 8080

spring:
  application:
    name: ${APPLICATION_NAME:Backend TodoList}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/todolist}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update